Update DOCS.md
hassio-addons/addon-zwave-js-ui pull request #419
Opened 2022-09-21 19:42 UTC by TheDK

Fix typo…

# Proposed Changes

> (Describe the changes and rationale behind them)

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2022-09-22 07:53 UTC, frenck requested changes

2022-09-22 07:53 UTC, frenck commented on zwave-js-ui/DOCS.md
> +to configure every aspect of your Z-Wave network. It provides a decoupled
This same typo is in the README and the README template (as the same text is used). Could you correct/keep them in sync?

../Frenck

2022-09-22 09:04 UTC, TheDK commented
Done

2022-10-23 09:52 UTC, TheDK commented
@frenck I corrected both docs - please feel free to merge.. :)

2022-10-23 10:39 UTC, frenck commented
@TheDK I'm aware, started the maintenance round on this add-on yesterday as well.. didn't get to complete the round yet, as weekend/family life got in the way.

2022-10-23 11:08 UTC, TheDK commented
No worries, just countering the stale bot in case you missed it…

2022-10-23 12:02 UTC, frenck approved these changes
Thanks, @TheDK 👍

2022-10-23 12:02 UTC, merged