Update to v8.8.5
hassio-addons/addon-zwave-js-ui pull request #467
Opened 2023-02-19 15:06 UTC by roblandry

# Proposed Changes
Upgrades Z-Wave JS UI to v8.8.5
  * https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.4
  * https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.5

## Related PR
> [#463 ](https://github.com/hassio-addons/addon-zwave-js-ui/pull/463)

2023-02-20 12:56 UTC, frenck requested changes

2023-02-20 12:56 UTC, frenck commented on zwave-js-ui/Dockerfile
> +        nodejs=18.14.1-r0 \
These changes are not related to this PR/bump and should thus not be in this PR.

2023-02-20 23:52 UTC, roblandry commented on zwave-js-ui/Dockerfile
> +        nodejs=18.14.1-r0 \
Unfortunately the build will not complete without these updates. The previous packages do not exist in alpine 3.17, and the build fails.
https://pkgs.alpinelinux.org/packages?name=nodejs&branch=v3.17&repo=&arch=&maintainer=
https://pkgs.alpinelinux.org/packages?name=python3-dev&branch=v3.17&repo=&arch=&maintainer=

2023-02-21 04:08 UTC, crawford commented on zwave-js-ui/Dockerfile
> +        nodejs=18.14.1-r0 \
Can you fix the dependencies in one PR (getting the pipeline working again) and then follow up with the bump in another?

2023-02-21 11:55 UTC, roblandry commented on zwave-js-ui/Dockerfile
> +        nodejs=18.14.1-r0 \
Yeah, when I get off work I'll submit a separate PR for the dependencies and update this one to only 8.8.5.

2023-02-21 22:08 UTC, roblandry commented on zwave-js-ui/Dockerfile
> +        nodejs=18.14.1-r0 \
Done. 
#470 
[7f9ae6f](https://github.com/hassio-addons/addon-zwave-js-ui/pull/467/commits/7f9ae6ff951ee25e2cb9cf1ee3454a043e06168a)

2023-02-22 17:05 UTC, frenck commented on zwave-js-ui/Dockerfile
> +        "https://github.com/zwave-js/zwave-js-ui/archive/v8.8.5.tar.gz" \
```suggestion
        "https://github.com/zwave-js/zwave-js-ui/archive/v8.8.6.tar.gz" \
```

2023-02-22 18:23 UTC, frenck approved these changes
Thanks, @roblandry 👍 

../Frenck

2023-02-22 18:23 UTC, merged